services:
  - type: web
    name: nexa-lead-manager
    env: python
    plan: starter
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn --config gunicorn.conf.py wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        value: sqlite:///nexa_leads.db
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: WHATSAPP_FROM
        sync: false
      - key: ADMIN_WHATSAPP
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: LOG_LEVEL
        value: INFO
